version: '3.8'

services:
  homelab-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelab-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - ./appsettings.Development.json:/app/appsettings.Development.json:ro
    restart: unless-stopped
    networks:
      - homelab-network

networks:
  homelab-network:
    driver: bridge
